# Generated by Django 5.1.2 on 2024-11-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_ajioproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajioproduct',
            name='date_scraped',
        ),
        migrations.AlterField(
            model_name='ajioproduct',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ajioproduct',
            name='rating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ajioproduct',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
