# Generated by Django 5.1.2 on 2024-11-28 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_remove_ajioproduct_date_scraped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajioproduct',
            name='date_scraped',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ajioproduct',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ajioproduct',
            name='rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ajioproduct',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
